// Импортируем шрифты и стили
import { Geist, Geist_Mono } from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Default export для RootLayout
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Добавляем компонент Speed Insights */}
        <SpeedInsights />
        {children}
      </body>
    </html>
  );
}

// Именованный экспорт metadata
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Removed invalid "scripts" object from the JavaScript file.

// Ensure dependencies are properly managed in package.json

